//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     Generation parameters:
//     - DataFilename: Patterns\Japanese\Japanese-Numbers.yaml
//     - Language: Japanese
//     - ClassName: NumbersDefinitions
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Recognizers.Definitions.Japanese
{
	using System;
	using System.Collections.Generic;

	public static class NumbersDefinitions
	{
		public const string LangMarker = "Jpn";
		public const char DecimalSeparatorChar = '.';
		public const string FractionMarkerToken = "";
		public const char NonDecimalSeparatorChar = ' ';
		public const string HalfADozenText = "";
		public const string WordSeparatorToken = "";
		public static readonly Dictionary<string, long> RoundNumberMap = new Dictionary<string, long>
		{
			{ "k", 1000 },
			{ "m", 1000000 },
			{ "g", 1000000000 },
			{ "t", 1000000000000 }
		};
		public static readonly Dictionary<char, long> RoundNumberMapJpn = new Dictionary<char, long>
		{
			{ '十', 10 },
			{ '百', 100 },
			{ '千', 1000 },
			{ '万', 10000 },
			{ '億', 100000000 },
			{ '兆', 1000000000000 }
		};
		public static readonly Dictionary<char, double> ZeroToNineMapJpn = new Dictionary<char, double>
		{
			{ '零', 0 },
			{ '一', 1 },
			{ '二', 2 },
			{ '三', 3 },
			{ '四', 4 },
			{ '五', 5 },
			{ '六', 6 },
			{ '七', 7 },
			{ '八', 8 },
			{ '九', 9 },
			{ '0', 0 },
			{ '1', 1 },
			{ '2', 2 },
			{ '3', 3 },
			{ '4', 4 },
			{ '5', 5 },
			{ '6', 6 },
			{ '7', 7 },
			{ '8', 8 },
			{ '9', 9 },
			{ '半', 0.5 }
		};
		public static readonly Dictionary<char, char> FullToHalfMapJpn = new Dictionary<char, char>
		{
			{ '０', '0' },
			{ '１', '1' },
			{ '２', '2' },
			{ '３', '3' },
			{ '４', '4' },
			{ '５', '5' },
			{ '６', '6' },
			{ '７', '7' },
			{ '８', '8' },
			{ '９', '9' },
			{ 'Ｇ', 'G' },
			{ 'Ｍ', 'M' },
			{ 'Ｔ', 'T' },
			{ 'Ｋ', 'K' },
			{ 'ｋ', 'k' }
		};
		public static readonly Dictionary<string, string> UnitMapJpn = new Dictionary<string, string>
		{
			{ "万万", "億" },
			{ "億万", "兆" },
			{ "万億", "兆" }
		};
		public static readonly IList<char> RoundDirectListJpn = new List<char>
		{
			'万',
			'億',
			'兆'
		};
		public const string ZeroToNineIntegerRegexJpn = @"[一二三四五六七八九]";
		public const string ZeroToNineJpnFullHalfRegexJpn = @"[\d１２３４５６７８９０]";
		public const string ZeroToNineJpnFullRegexJpn = @"[\d1234567890]";
		public static readonly string DigitNumRegex = $@"{ZeroToNineJpnFullHalfRegexJpn}+";
		public const string RoundNumberIntegerRegexJpn = @"[十百千万億兆]";
		public static readonly string AllIntRegexJpn = $@"(({ZeroToNineIntegerRegexJpn}|{ZeroToNineJpnFullHalfRegexJpn}|[十])\s*{RoundNumberIntegerRegexJpn}){{1,2}}\s*(\s*[以上]?)";
		public static readonly string OrdinalRegexJpn = $@"(だい|第){AllIntRegexJpn}";
		public static readonly string OrdinalNumbersRegex = $@"(だい|第){ZeroToNineJpnFullHalfRegexJpn}+";
		public const string NegativeNumberTermsRegexJpn = @"(マイナス)";
		public const string NegativeNumberTermsRegexNum = @"(?<![-－])[-－]";
		public static readonly string NegativeNumberSignRegex = $@"^{NegativeNumberTermsRegexJpn}.*|^{NegativeNumberTermsRegexNum}.*";
		public const string PointRegexJpnStr = @"[\.．]";
		public static readonly string PointRegexJpn = $@"{PointRegexJpnStr}";
		public static readonly string AllFloatRegexJpn = $@"{NegativeNumberTermsRegexJpn}?{AllIntRegexJpn}\s*{PointRegexJpnStr}\s*[一二三四五六七八九](\s*{ZeroToNineIntegerRegexJpn})*";
		public static readonly string SimplePercentageRegex = $@"({ZeroToNineIntegerRegexJpn}|{AllFloatRegexJpn}|{AllIntRegexJpn})\s*パ\s*ー\s*セ\s*ン\s*ト";
		public const string PercentageRegex = @".+(?=パ\s*ー\s*セ\s*ン\s*ト)|.*(?=[％%])";
		public static readonly string NumbersPercentagePointRegex = $@"({ZeroToNineJpnFullHalfRegexJpn}|{ZeroToNineJpnFullRegexJpn})+([\.．]({ZeroToNineJpnFullHalfRegexJpn}|{ZeroToNineJpnFullRegexJpn})+)?\s*パ\s*ー\s*セ\s*ン\s*ト";
		public static readonly string AllFractionNumber = $@"{NegativeNumberTermsRegexJpn}?(({ZeroToNineJpnFullHalfRegexJpn}+|{NegativeNumberTermsRegexJpn}?({ZeroToNineJpnFullHalfRegexJpn}+|{AllIntRegexJpn})\s*分\s*の\s*{NegativeNumberTermsRegexJpn}?({ZeroToNineJpnFullHalfRegexJpn}+|{AllIntRegexJpn})";
		public static readonly string FractionNotationSpecialsCharsRegex = $@"({NegativeNumberTermsRegexNum}\s*)?{ZeroToNineJpnFullHalfRegexJpn}+\s+{ZeroToNineJpnFullHalfRegexJpn}+[/／]{ZeroToNineJpnFullHalfRegexJpn}+";
		public static readonly string FractionNotationRegex = $@"({NegativeNumberTermsRegexNum}\s*)?{ZeroToNineJpnFullHalfRegexJpn}+[/／]{ZeroToNineJpnFullHalfRegexJpn}+";
		public static readonly string NumbersSpecialsChars = $@"(({NegativeNumberTermsRegexNum}|{NegativeNumberTermsRegexJpn})\s*)?{ZeroToNineJpnFullHalfRegexJpn}+";
		public static readonly string NumbersSpecialsCharsWithSuffix = $@"{NegativeNumberTermsRegexNum}?{ZeroToNineJpnFullHalfRegexJpn}+\s*(K|k|M|G|T|Ｍ|Ｋ|ｋ|Ｇ|Ｔ)";
		public static readonly string DottedNumbersSpecialsChar = $@"{NegativeNumberTermsRegexNum}?{ZeroToNineJpnFullHalfRegexJpn}{{1,3}}([,，]{ZeroToNineJpnFullHalfRegexJpn}{{3}})+";
		public static readonly string NumbersWithHalfDozen = $@"半ダース";
		public static readonly string NumbersWithDozen = $@"({ZeroToNineJpnFullRegexJpn}|{ZeroToNineJpnFullHalfRegexJpn}|{ZeroToNineIntegerRegexJpn})ダース";
		public static readonly string DoubleSpecialsChars = $@"(?<!({ZeroToNineJpnFullHalfRegexJpn}+[\.．]{ZeroToNineJpnFullHalfRegexJpn}*))({NegativeNumberTermsRegexNum}\s*)?{ZeroToNineJpnFullHalfRegexJpn}+[\.．]{ZeroToNineJpnFullHalfRegexJpn}+(?!{ZeroToNineJpnFullHalfRegexJpn}*[\.．]{ZeroToNineJpnFullHalfRegexJpn}+)";
		public static readonly string DoubleSpecialsCharsWithNegatives = $@"(?<!({ZeroToNineJpnFullHalfRegexJpn}+|\.\.|．．))({NegativeNumberTermsRegexNum}\s*)?[\.．]{ZeroToNineJpnFullHalfRegexJpn}+(?!{ZeroToNineJpnFullHalfRegexJpn}*([\.．]{ZeroToNineJpnFullHalfRegexJpn}+))";
		public static readonly string SimpleDoubleSpecialsChars = $@"({NegativeNumberTermsRegexNum}\s*)?{ZeroToNineJpnFullHalfRegexJpn}{{1,3}}([,，]{ZeroToNineJpnFullHalfRegexJpn}{{3}})+[\.．]{ZeroToNineJpnFullHalfRegexJpn}+";
	}
}